name: Daily build
on:
  schedule:
    - cron: 0 0 * * * # Every day at midnight (UTC)
jobs:
  daily-build:
    runs-on: windows-latest
    strategy:
      matrix:
        rid: [linux_x64, win_x64, osx_x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore
      run: ./build.cmd Restore

    - name: Build
      run: ./build.cmd Publish --runtime ${{matrix.rid}} --skip Restore
      
    - name: Zip
      run: ./build.cmd Zip --runtime ${{matrix.rid}} --skip Publish

    - name: Save
      uses: actions/upload-artifact@v3
      with:
        name: beutl_${{matrix.rid}}
        path: ./artifacts/
